name: showcase_tutorial
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 1.1.1
homepage: https://github.com/abdelrahman-abied/showcase_tutorial
issue_tracker: https://github.com/abdelrahman-abied/showcase_tutorial/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


